// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MessagingController is an autogenerated mock type for the MessagingController type
type MessagingController struct {
	mock.Mock
}

// GetConversationHistory provides a mock function with given fields: c
func (_m *MessagingController) GetConversationHistory(c *gin.Context) {
	_m.Called(c)
}

// SendMessage provides a mock function with given fields: c
func (_m *MessagingController) SendMessage(c *gin.Context) {
	_m.Called(c)
}

// NewMessagingController creates a new instance of MessagingController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagingController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagingController {
	mock := &MessagingController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
