// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// PingController is an autogenerated mock type for the PingController type
type PingController struct {
	mock.Mock
}

// Ping provides a mock function with given fields: context
func (_m *PingController) Ping(context *gin.Context) {
	_m.Called(context)
}

// NewPingController creates a new instance of PingController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingController(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingController {
	mock := &PingController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
